### ISSUE TITLE
`conj` should delegate to `torch.conj_physical`

### ISSUE THREAD

**Issue by lucascolley** [data-apis/array-api-compat#173]
See https://github.com/scipy/scipy/pull/20772#issuecomment-2268760340

**Comment by asmeurer** [comment]
So the issue is that `torch.conj` works by setting a conjugation bit, which means `np.asarray(torch.conj(x))` won't work. `torch.conj_physical` does an actual conjugation. This is considerably less efficient (`torch.conj` runs in constant time whereas `conj_physical` has to compute the conjugation), but it seems that things like `np.asarray` or even `__dlpack__` won't work on tensors with the conjugation bit. 

```py
>>> a = torch.linspace(0, 10, 10000) + torch.linspace(0, 10, 10000)*1j
>>> np.asarray(torch.conj(a))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/miniconda3/envs/array-apis/lib/python3.12/site-packages/torch/_tensor.py", line 1087, in __array__
    return self.numpy()
           ^^^^^^^^^^^^
RuntimeError: Can't call numpy() on Tensor that has conjugate bit set. Use tensor.resolve_conj().numpy() instead.
>>> torch.conj(a).__dlpack__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/miniconda3/envs/array-apis/lib/python3.12/site-packages/torch/_tensor.py", line 1480, in __dlpack__
    raise RuntimeError("Can't export tensors with the conjugate bit set")
RuntimeError: Can't export tensors with the conjugate bit set
```

This seems like something that the array API ought to be able to support. But maybe the issue is that PyTorch should just realize the conjugation automatically when converting to NumPy or DLPack instead of requiring the user to do it.

**Comment by rgommers** [comment]
> But maybe the issue is that PyTorch should just realize the conjugation automatically when converting to NumPy or DLPack instead of requiring the user to do it.

Yes, I think that would be the correct thing to do, rather than PyTorch erroring out.

**Comment by asmeurer** [comment]
Well the error seems to be intentional, so there might be an explicit design decision there.
