### ISSUE TITLE
Minimum NumPy version support?

### ISSUE THREAD

**Issue by thomasjpfan** [data-apis/array-api-compat#21]
Currently `unique_*` passes `equal_nan` to `np.unique`, which was introduced in [NumPy 1.24](https://numpy.org/doc/stable/reference/generated/numpy.unique.html) (released 12/2022).

https://github.com/data-apis/array-api-compat/blob/945609e64536a88d0f507d222140f97fa68776da/array_api_compat/common/_aliases.py#L184-L190

Does `array-api-compat` want to support older versions of NumPy?

**Comment by rgommers** [comment]
+1 for supporting older versions where possible. Probably back to all supported versions according to NEP 29 - so testing NumPy 1.21 would be useful. That may mean a few things don't work of course - a non-default value of the `equal_nan` keyword here may just raise an exception I think.

**Comment by asmeurer** [comment]
The mean reason I hadn't tested older NumPy's is because we can't use `NPY_PROMOTION_STATE=weak`, so a lot of tests fail with promotion issues. But I can try to create a longer xfails file for NumPy 1.21 and hopefully it will still catch issues like this one.

**Comment by asmeurer** [comment]
Well testing was a good idea because I found at least one other broken thing (`np._CopyMode` in `asarray`). Also, it looks like the [docs for `np.unique`](https://numpy.org/doc/stable/reference/generated/numpy.unique.html) are wrong. They say `equal_nan` was introduced in NumPY 1.24 but it was introduced in 1.23.

**Comment by asmeurer** [comment]
Which cupy versions should we support?

**Comment by asmeurer** [comment]
So it turns out that `equal_nan` isn't the only thing not supported in NumPy 1.21 https://github.com/data-apis/array-api-compat/pull/25/files#diff-b49d3c594dcd0f66d1e1534d2bfb4aa16efd3b2973fe81e97c00e14e03ab3e93R51. Here are the things that won't work in NumPy 1.21:

- `unique_*` will not compare nans as unequal.
- `finfo()` has no `smallest_normal`.
- No `from_dlpack` or `__dlpack__`.
- `argmax()` and `argmin()` do not have `keepdims`.
- `qr()` doesn't support matrix stacks.
- `asarray()` doesn't support `copy=True` (`copy=False` is not supported even in the latest NumPy).
- Type promotion behavior will be value based for 0-D arrays (and there is no `NPY_PROMOTION_STATE=weak` to disable this).

If any of these are an issue for you, I recommend bumping your minimum NumPy version, as I do not intend to work around them here (I suppose we could work around some of the simpler ones if it's *really* important).

**Comment by thomasjpfan** [comment]
The items listed in https://github.com/data-apis/array-api-compat/issues/21#issuecomment-1459038631 that do not work in NumPy 1.21 are not issues with scikit-learn's codebase.

**Comment by asmeurer** [comment]
We now support and test numpy 1.21.
