### ISSUE TITLE
Support `cupy.ndarray`?

### ISSUE THREAD

**Issue by leofang** [data-apis/array-api-compat#3]
Create an issue and assign to self so I don't forget. cc: @kmaehashi @asi1024 @emcastillo

**Comment by leofang** [comment]
Oh I can't assign...

**Comment by rgommers** [comment]
> Oh I can't assign...

Fixed by adding this repo to the "all-members" team

**Comment by asmeurer** [comment]
Presumably we will want to support cupy, since cupy has the exact same issues as NumPy, namely the namespace isn't quite array API compatible, and the cupy.array_api namespace uses a separate array object, which makes it difficult to work with. 

The only alternative would be if cupy wanted to make changes directly to make itself array API compatible, so that there is no need for a wrapper library. This would most likely imply breaking from NumPy, at least for a bit. I expect NumPy will eventually make its main namespace array API compatible, but it will take some time, especially for things that are breaking changes. 

I think technically this should be doable, in this library. We just need to factor out the uses of `np` to support numpy or cupy. I need to think about the cleanest way to do this in the code, which doesn't require too much boilerplate, and also doesn't force this library to hard depend on NumPy or CuPy if they are not already installed.
